name: Build/Release

on:
  push:
    branches:
      - '*'  # Ejecutar en cualquier push
    tags:
      - 'v*'  # Ejecutar cuando se crea un tag que sigue el patrón "vX.X.X"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
            node-version: 16

      - name: Electron-builder compiler action
        uses: x6pnda/action-electron-compiler@v1.0.1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            release: ${{ startsWith(github.ref, 'refs/tags/v') }}  # Se libera solo si es un tag
            package_manager: NPM
            skip_build: false

      # Solo corre 'make' si es un tag
      - name: Run Make for release
        if: startsWith(github.ref, 'refs/tags/')  # Verificar si es un tag
        run: make
